server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XuKK-OUC/microservicecloud-config.git #GitHub上面的git仓库名字

